{
 "title": "Bot",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Общее число транзакций",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "transactions_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество исключений",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "exceptions_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Динамическая цена газа",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "current_gas_price", "legendFormat": "__auto" }
   ]
  }
 ]
}