{
 "title": "Simulation",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Количество симуляций",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "simulated_trades_total{status=\"success\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "simulated_trades_total{status=\"failure\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Прибыль по симуляциям",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "simulated_profit{module=\"arbiter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время симуляции сделки",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "simulated_trade_duration_seconds",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}